"""Release state — what this build of PhysMAP is allowed to claim.

Three states. The state is a CONSTANT fixed at release time. It is deliberately
**not** derived from which files happen to be present on disk: a command must not
appear or disappear because a data directory was copied in. That would make the
package's claims a function of the user's filesystem instead of a function of what
was actually reviewed and released.

  GUARDRAIL           closure/observability method, the NACA x/D regression, and the
                      v0.4 seven-vehicle benchmark. No causal-materiality claim.

  CAUSAL_PREVIEW      the above, plus the causal-materiality API exercised on
                      synthetic and unit fixtures only. No precision/recall/F1,
                      no expected_metrics.json, and NO `reproduce` subcommand.

  NAFEMS_REPRODUCTION the above, plus the complete redistributable benchmark:
                      a locked reconstruction protocol, independent experimental
                      truth, a geometry-appropriate forced-convection
                      counterfactual, and expected metrics.

Promotion to NAFEMS_REPRODUCTION is gated by `physmap.benchmarks.readiness`, which
is a RELEASE-ENGINEERING check run in CI before this constant may be changed. It is
never consulted at runtime to decide what the CLI offers.

Why the causal numbers in the NAFEMS abstract are not reproduced here: the original
study's inputs are not available, and the experimental-truth basis is unresolved.
A reconstruction under a locked protocol will produce its OWN numbers. Those will
not be the abstract's numbers, and this package never presents them as such.
"""

from __future__ import annotations

from enum import Enum

__all__ = [
    "ReleaseState",
    "CURRENT_RELEASE_STATE",
    "EvidenceState",
    "emits_performance_metrics",
    "has_reproduce_command",
    "causal_api_is_preview",
]


class ReleaseState(str, Enum):
    GUARDRAIL = "guardrail"
    CAUSAL_PREVIEW = "causal_preview"
    NAFEMS_REPRODUCTION = "nafems_reproduction"


#: Set at release time. Changing this requires the readiness gate to pass in CI.
CURRENT_RELEASE_STATE: ReleaseState = ReleaseState.CAUSAL_PREVIEW


class EvidenceState(str, Enum):
    """What kind of thing produced a result. Carried on every causal assessment and
    screen so no emitted artifact can be mistaken for a validated performance claim."""

    #: Generated by a synthetic or unit fixture. Demonstrates mechanics, proves nothing
    #: about the physical world.
    SYNTHETIC_FIXTURE = "synthetic_fixture"
    #: A stated case: the refusal logic and its reason code, with no evidence inputs
    #: behind it. The two screened-out vehicles are this.
    DECLARATIVE = "declarative"
    #: Backed by checked-in evidence inputs with cleared provenance.
    MEASURED = "measured"


def emits_performance_metrics(state: ReleaseState | None = None) -> bool:
    """True only where precision/recall/F1 may legitimately be produced."""
    return (state or CURRENT_RELEASE_STATE) is ReleaseState.NAFEMS_REPRODUCTION


def has_reproduce_command(state: ReleaseState | None = None) -> bool:
    """Whether the CLI exposes `reproduce`. Static per release, by design."""
    return (state or CURRENT_RELEASE_STATE) is ReleaseState.NAFEMS_REPRODUCTION


def causal_api_is_preview(state: ReleaseState | None = None) -> bool:
    """True where the causal-materiality API ships but carries no performance claim."""
    return (state or CURRENT_RELEASE_STATE) is ReleaseState.CAUSAL_PREVIEW
