"""Phase-2C defeasible-adjudication aggregator.

Per the v0.2 architecture refactor spec, Part 4:

> The Disposition is NOT an accumulation/vote of factors. It is a DEFEASIBLE
> ADJUDICATION of them. ... A weakener can be OFFSET by other evidence, made
> NON-DISPOSITIVE by agreement, MODULATED by threshold distance; a defeater
> can be SUSTAINED but JUSTIFIED with residual-risk rationale.

This module is the Phase-2 replacement for the simple Phase-1
`AnyFired`/`CorpusGated`/`WeightedVote` aggregators (Step 6) and for
the Phase-2A default action-class chooser in `assessment_v06.py`. It
takes the per-point WeakenerAnnotations and decision signals and
produces:

  * action_class            ∈ v0.6 DISPOSITION_ACTION_CLASSES
  * residual_risk_justification (free text; required when
                              action_class == 'accept-residual-risk')
  * offset_rationales       — OffsetRationale nodes naming the
                              weakeners that were offset and why

ACTION-CLASS SELECTION RULES (the Phase-2C policy):

  0 weakeners                                       -> accept-residual-risk
  only literature (OutOfValidatedRange) fires       -> characterize-region
    (the v0.3 NACA finding: literature bound has geometry-coarse
    precision; describe the region before deploying — see
    docs/findings/PhysMAP_D3_NACA_EntranceRegion_Findings_v0_1.md)
  novelty alone (distance / gp_variance / ensemble) -> acquire-validation
    (input baselines fire; need more validation data in the OOD region)
  novelty + literature fire                         -> restrict-cou
    (both bases agree something is wrong; narrow the CoU)
  corpus-error alone                                -> accept-residual-risk
    (training-distribution error magnitude; explainable as known noise)
  3+ distinct patterns / fallback                   -> change-cou
    (multiple uncorrelated weakeners; model swap or major change indicated)

These rules implement the spec's CHARACTER of defeasibility — the
controlled-vocab outputs are the v0.6-correct way to express "accept
with conditions" / "restrict" / "review" / etc. (the spec's abstract
verbs from the merged design map to these 5 strings via the disposition
SHACL pack).

OFFSETS are NOT generated by the default rules. They're a Phase-2C+
extension point: an OffsetRule callable can be plugged into the
adjudicator to produce OffsetRationale nodes (e.g., "agreement-non-
dispositive" when multiple detectors fire on the same Discrepancy by
construction, or "threshold-distance-modulates" when score barely
exceeds tau). Future weakener-engine patterns hook in here.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable, Sequence

from physmap.pipeline.assessment_v06 import (
    DISPOSITION_ACTION_CLASSES,
    OffsetRationaleNode,
    WeakenerAnnotationNode,
)
from physmap.pipeline.core import DetectorResult


# Pattern-id buckets (one entry per pattern produced by
# `assessment_v06._PATTERN_ID_BY_DETECTOR`). Keep in sync with that
# mapping; any drift here makes the adjudicator's rules vacuously
# inapplicable.
NOVELTY_PATTERNS = frozenset({
    "InputOutOfTrainingDistribution",
    "SurrogateVarianceExceedsThreshold",
    "EnsembleDisagreement",
})
LITERATURE_PATTERN = "OutOfValidatedRange"
CORPUS_ERROR_PATTERN = "CorpusErrorMagnitudeAboveThreshold"


# ── offset-rule plug-in (Phase-2C+ extension point) ─────────────────────────

OffsetRuleFn = Callable[
    [Sequence[WeakenerAnnotationNode], dict[str, DetectorResult], str],
    list[OffsetRationaleNode],
]


@dataclass(frozen=True)
class OffsetRule:
    """A named, pluggable rule that may emit OffsetRationale nodes from a
    set of weakeners + the underlying decision signals + the
    Discrepancy/Disposition id. The default adjudicator ships with NO
    rules — Phase-2C is intentionally conservative on offsets. Add rules
    via `DefeasibleAdjudicator(offset_rules=[...])` to extend."""
    name: str
    apply: OffsetRuleFn


# ── adjudication result ─────────────────────────────────────────────────────

@dataclass(frozen=True)
class AdjudicationResult:
    """Output of a single per-point adjudication. Populates the
    Disposition's actionClass + residualRiskJustification and the
    OffsetRationale node list the v0.6 subgraph carries alongside."""
    action_class: str
    residual_risk_justification: str
    offset_rationales: list[OffsetRationaleNode] = field(default_factory=list)
    surviving_weakener_ids: list[str] = field(default_factory=list)
    rule_fired: str = ""    # name of the action-class rule that fired

    def __post_init__(self) -> None:
        if self.action_class not in DISPOSITION_ACTION_CLASSES:
            raise ValueError(
                f"AdjudicationResult.action_class={self.action_class!r} not "
                f"in v0.6 controlled vocab {DISPOSITION_ACTION_CLASSES}."
            )
        # accept-residual-risk REQUIRES residual_risk_justification, by
        # both the spec (PART 4) and natural-language sense. SHACL doesn't
        # pin this (it leaves residualRiskJustification optional at the
        # NodeShape level), but the adjudicator is the right place to
        # enforce it — wrong omission here would be a silent disposition.
        if (self.action_class == "accept-residual-risk"
                and not self.residual_risk_justification.strip()):
            raise ValueError(
                "AdjudicationResult: action_class='accept-residual-risk' "
                "requires non-empty residual_risk_justification. "
                "(Acceptance without rationale is the failure mode the "
                "spec's defeasibility discipline guards against.)"
            )


# ── the adjudicator ─────────────────────────────────────────────────────────

@dataclass
class DefeasibleAdjudicator:
    """Phase-2C defeasible-adjudication aggregator. Reads per-point
    WeakenerAnnotations (from the Phase-1 → v0.6 mapper) and decision
    signals, applies offset rules, and emits an AdjudicationResult.

    Designed to be plugged into `assessment_v06.assessment_to_v06_subgraph`
    via the `adjudicator` kwarg (Phase-2C overrides the Phase-2A default
    chooser).
    """
    name: str = "defeasible_adjudicator"
    offset_rules: list[OffsetRule] = field(default_factory=list)

    def adjudicate(
        self,
        weakeners: Sequence[WeakenerAnnotationNode],
        decision_signals: dict[str, DetectorResult],
        discrepancy_id: str,
    ) -> AdjudicationResult:
        # Step 1: apply offset rules. Each rule returns OffsetRationales
        # that point at CredibilityFactor ids (refers_to_factor). The
        # mapping from rationale -> weakener is by-pattern: any
        # OffsetRationale whose refers_to_factor matches a weakener's
        # corresponding factor id is considered to offset that weakener.
        offsets: list[OffsetRationaleNode] = []
        for rule in self.offset_rules:
            offsets.extend(rule.apply(weakeners, decision_signals, discrepancy_id))

        # Step 2: filter the weakener set down to "surviving" (not offset).
        # An OffsetRationale refers to a CredibilityFactor by id; our
        # WeakenerAnnotation ids embed the detector name (Phase-2A
        # convention: `weakener:.../<detector_name>`), and the
        # factor ids embed the same suffix. Match by id-suffix.
        offset_factor_ids = {o.refers_to_factor for o in offsets}
        def _is_offset(w: WeakenerAnnotationNode) -> bool:
            # Phase-2A id convention: weakener:.../detector and factor:.../detector
            # share the trailing detector segment. Strip the "weakener:" prefix.
            detector_segment = w.id_.rsplit("/", 1)[-1]
            for fid in offset_factor_ids:
                if fid.endswith(f"/{detector_segment}"):
                    return True
            return False

        surviving = [w for w in weakeners if not _is_offset(w)]

        # Step 3: action-class selection (the v0.6 controlled vocab dispatch).
        action_class, residual_just, rule_fired = self._select_action_class(surviving)

        return AdjudicationResult(
            action_class=action_class,
            residual_risk_justification=residual_just,
            offset_rationales=offsets,
            surviving_weakener_ids=[w.id_ for w in surviving],
            rule_fired=rule_fired,
        )

    # ── action-class rules ──────────────────────────────────────────────────

    def _select_action_class(
        self, surviving: Sequence[WeakenerAnnotationNode],
    ) -> tuple[str, str, str]:
        """Map surviving weakeners → (action_class, residual_just, rule_fired).
        The five-controlled-vocab dispatch documented in the module docstring.
        """
        if not surviving:
            return (
                "accept-residual-risk",
                "No weakeners surviving adjudication; accept with residual "
                "risk per default cautious policy. (No defeaters fired or all "
                "were offset.)",
                "no-weakeners",
            )

        patterns = {w.pattern_id for w in surviving}
        has_novelty = bool(patterns & NOVELTY_PATTERNS)
        has_literature = LITERATURE_PATTERN in patterns
        has_corpus_error = CORPUS_ERROR_PATTERN in patterns

        # Only the literature signal fires (no novelty, no corpus-error).
        # This is the NACA misaligned-bound case per the v0.3 findings:
        # the literature bound is geometry-coarse; characterize the region.
        if patterns == {LITERATURE_PATTERN}:
            return (
                "characterize-region",
                "",
                "literature-only-misaligned-bound",
            )

        # Novelty + literature: both bases agree something is OOD. Restrict.
        if has_novelty and has_literature:
            return (
                "restrict-cou",
                "",
                "novelty-and-literature-agree",
            )

        # Novelty alone (input distribution flags but no literature concern):
        # acquire more validation data in the OOD region.
        if has_novelty and not has_literature and not has_corpus_error:
            return (
                "acquire-validation",
                "",
                "novelty-alone",
            )

        # Corpus k-NN error alone — explainable noise, accept with risk.
        if patterns == {CORPUS_ERROR_PATTERN}:
            return (
                "accept-residual-risk",
                "Sole weakener is training-distribution corpus k-NN error "
                "magnitude. This is a fit-quality signal, not an OOD or "
                "literature-validity signal; accept with residual risk.",
                "corpus-error-alone",
            )

        # Fallback: multi-pattern complex case (literature + corpus-error,
        # or three+ patterns). The CoU itself may be miscast — change-cou.
        return (
            "change-cou",
            "",
            "complex-multi-pattern-fallback",
        )


# ── built-in offset rules ───────────────────────────────────────────────────
#
# Phase-2C ships these as optional library entries; the default
# DefeasibleAdjudicator has them DISABLED (offset_rules=[]) until each
# is exercised by a downstream gate that wants the looser policy. The
# spec lists three offset mechanisms — implementing them as named rules
# makes their use deliberate.


def agreement_non_dispositive_rule(
    weakeners: Sequence[WeakenerAnnotationNode],
    decision_signals: dict[str, DetectorResult],
    discrepancy_id: str,
) -> list[OffsetRationaleNode]:
    """When BOTH a novelty pattern AND the literature pattern fire on the
    same Discrepancy, the AGREEMENT makes each weakener
    non-dispositive — the two signals aren't independent voters; they're
    different cuts of the same OOD condition. Per the v0.6 vocab
    (`agreementMakesNonDispositive`), the literature weakener is the one
    typically offset (since the input-distribution signal carries the
    independent evidential weight).
    """
    patterns = {w.pattern_id for w in weakeners}
    has_novelty = bool(patterns & NOVELTY_PATTERNS)
    has_literature = LITERATURE_PATTERN in patterns
    if not (has_novelty and has_literature):
        return []
    # Find the literature weakener and emit an OffsetRationale for the
    # corresponding factor.
    out: list[OffsetRationaleNode] = []
    for w in weakeners:
        if w.pattern_id == LITERATURE_PATTERN:
            detector_segment = w.id_.rsplit("/", 1)[-1]
            base = w.id_.replace("weakener:", "").rsplit("/", 1)[0]
            factor_id = f"factor:{base}/{detector_segment}"
            offset_id = f"offset:{base}/{detector_segment}/agreement-non-dispositive"
            out.append(OffsetRationaleNode(
                id_=offset_id,
                refers_to_factor=factor_id,
                justification=(
                    "agreementMakesNonDispositive: literature weakener "
                    "(OutOfValidatedRange) co-fires with an independent "
                    "input-distribution novelty weakener on the same "
                    "Discrepancy. The novelty signal carries the "
                    "evidential weight; the literature signal is "
                    "non-dispositive by agreement."
                ),
            ))
    return out


AGREEMENT_NON_DISPOSITIVE = OffsetRule(
    name="agreement-non-dispositive",
    apply=agreement_non_dispositive_rule,
)


__all__ = [
    "NOVELTY_PATTERNS",
    "LITERATURE_PATTERN",
    "CORPUS_ERROR_PATTERN",
    "OffsetRule",
    "OffsetRuleFn",
    "AdjudicationResult",
    "DefeasibleAdjudicator",
    "agreement_non_dispositive_rule",
    "AGREEMENT_NON_DISPOSITIVE",
]
