"""Bundled open closure-index data (package resource).

Holds `closure_index.json` — public coverage metadata for every known closure
(id, name, family, geometry, coordinates, citation, aliases). NO ranges, NO
provenance, NO disposition content. Generated by
`physmap.closures.index.build_index_json()` and shipped in the core wheel.
"""
