#!/usr/bin/env python3
"""Generate an OpenFOAM case: laminar mixed convection, vertical pipe, uniform wall flux.

Geometry and boundary condition follow Mohammed & Salman (2008) as stated in the paper:
vertical circular cylinder, D = 30 mm inside diameter, 900 mm heated length (L/D = 30),
constant wall heat flux, air, upward (assisting) flow, laminar.

Axisymmetric wedge: radial = x, axial = y (vertical, flow +y), wedge opens in z.
Gravity is -y for the buoyancy-on case and exactly zero for its matched pair. **That is
the only difference between a pair.**

This is a DEVELOPMENT / DEMONSTRATION case. It is not a reproduction of the original
study, and no scoring choice is made anywhere in it.
"""
from __future__ import annotations
import argparse, json, math, pathlib, shutil

# air at ~300 K, 1 atm -- matches the buoyantCavity thermophysical form
MU, PR, CP, MW = 1.831e-05, 0.705, 1004.4, 28.96
T0, P0 = 300.0, 101325.0
R_SPEC = 8314.0 / MW
RHO = P0 / (R_SPEC * T0)
NU = MU / RHO
K_TH = MU * CP / PR
BETA = 1.0 / T0
D, L = 0.030, 0.900
RAD = D / 2.0
HALF_ANGLE_DEG = 2.5


def derived(Re: float, q_w: float) -> dict:
    U = Re * NU / D
    Gr = 9.81 * BETA * q_w * D**4 / (K_TH * NU**2)   # UHF Grashof, Gr*
    Ra = Gr * PR
    return {"U_inlet": U, "Gr_star": Gr, "Ra_star": Ra, "Ri": Gr / Re**2,
            "rho": RHO, "nu": NU, "k": K_TH, "Pr": PR}


HEAD = """/*--------------------------------*- C++ -*----------------------------------*\\
| generated by cfd/gencase.py -- do not hand-edit                             |
\\*---------------------------------------------------------------------------*/
FoamFile
{{
    version     2.0;
    format      ascii;
    class       {cls};
    object      {obj};
}}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
"""


def w(path: pathlib.Path, cls: str, obj: str, body: str, loc: str | None = None):
    path.parent.mkdir(parents=True, exist_ok=True)
    head = HEAD.format(cls=cls, obj=obj)
    if loc:
        head = head.replace("    object", f'    location    "{loc}";\n    object')
    path.write_text(head + body + "\n\n// ***************************************************************** //\n")


def blockmesh(nr: int, ny: int) -> str:
    zo = RAD * math.tan(math.radians(HALF_ANGLE_DEG))
    return f"""scale 1;

vertices
(
    (0      0    0)          // 0 axis inlet
    ({RAD}  0    {zo:.8f})   // 1 wall inlet +z
    ({RAD}  0   -{zo:.8f})   // 2 wall inlet -z
    (0      0    0)          // 3 axis inlet (collapsed)
    (0      {L}  0)          // 4 axis outlet
    ({RAD}  {L}  {zo:.8f})   // 5 wall outlet +z
    ({RAD}  {L} -{zo:.8f})   // 6 wall outlet -z
    (0      {L}  0)          // 7 axis outlet (collapsed)
);

// right-handed: local x is radial (0->1), local y circumferential (1->2, -z),
// local z axial (0->4, +y). x_hat cross (-z_hat) = +y_hat.
blocks
(
    hex (0 1 2 3 4 5 6 7) ({nr} 1 {ny}) simpleGrading (1 1 1)
);

edges ();

boundary
(
    inlet   {{ type patch; faces ((0 3 2 1)); }}
    outlet  {{ type patch; faces ((4 5 6 7)); }}
    wall    {{ type wall;  faces ((1 2 6 5)); }}
    front   {{ type wedge; faces ((3 7 6 2)); }}
    back    {{ type wedge; faces ((0 1 5 4)); }}
    axis    {{ type empty; faces ((0 4 7 3)); }}
);

mergePatchPairs ();"""


def build(out: pathlib.Path, Re: float, q_w: float, gravity: bool,
          nr: int, ny: int, n_iter: int, write_interval: int) -> dict:
    if out.exists():
        shutil.rmtree(out)
    d = derived(Re, q_w)
    U = d["U_inlet"]

    w(out / "system/blockMeshDict", "dictionary", "blockMeshDict", blockmesh(nr, ny), "system")
    w(out / "system/controlDict", "dictionary", "controlDict", f"""application     buoyantSimpleFoam;
startFrom       startTime;
startTime       0;
stopAt          endTime;
endTime         {n_iter};
deltaT          1;
writeControl    timeStep;
writeInterval   {write_interval};
purgeWrite      2;
writeFormat     ascii;
writePrecision  8;
writeCompression off;
timeFormat      general;
timePrecision   6;
runTimeModifiable false;

functions
{{
    wallHeatFlux
    {{
        type            wallHeatFlux;
        libs            (fieldFunctionObjects);
        patches         (wall);
        writeControl    writeTime;
        log             true;
    }}
    inletOutletBalance
    {{
        type            surfaceFieldValue;
        libs            (fieldFunctionObjects);
        regionType      patch;
        name            outlet;
        operation       weightedAverage;
        weightField     phi;
        fields          (T);
        writeFields     false;
        writeControl    timeStep;
        writeInterval   {write_interval};
        log             false;
    }}
    inletTemp
    {{
        type            surfaceFieldValue;
        libs            (fieldFunctionObjects);
        regionType      patch;
        name            inlet;
        operation       weightedAverage;
        weightField     phi;
        fields          (T);
        writeFields     false;
        writeControl    timeStep;
        writeInterval   {write_interval};
        log             false;
    }}
    massFlow
    {{
        type            surfaceFieldValue;
        libs            (fieldFunctionObjects);
        regionType      patch;
        name            outlet;
        operation       sum;
        fields          (phi);
        writeFields     false;
        writeControl    timeStep;
        writeInterval   {write_interval};
        log             false;
    }}
    residuals
    {{
        type            solverInfo;
        libs            (utilityFunctionObjects);
        fields          (U h p_rgh);
        writeResidualFields false;
        writeControl    timeStep;
        writeInterval   1;
    }}
}}""")

    w(out / "system/fvSchemes", "dictionary", "fvSchemes", """ddtSchemes      { default steadyState; }
gradSchemes     { default Gauss linear; }
divSchemes
{
    default         none;
    div(phi,U)      bounded Gauss linearUpwind grad(U);
    div(phi,h)      bounded Gauss limitedLinear 1;
    div(phi,e)      bounded Gauss limitedLinear 1;
    div(phi,K)      bounded Gauss limitedLinear 1;
    div(phi,Ekp)    bounded Gauss limitedLinear 1;
    div(((rho*nuEff)*dev2(T(grad(U))))) Gauss linear;
}
laplacianSchemes { default Gauss linear corrected; }
interpolationSchemes { default linear; }
snGradSchemes   { default corrected; }""")

    w(out / "system/fvSolution", "dictionary", "fvSolution", """solvers
{
    p_rgh
    {
        solver          GAMG;
        tolerance       1e-10;
        relTol          0.01;
        smoother        GaussSeidel;
    }
    "(U|h|e|k|epsilon|omega)"
    {
        solver          PBiCGStab;
        preconditioner  DILU;
        tolerance       1e-10;
        relTol          0.1;
    }
}

SIMPLE
{
    momentumPredictor yes;
    nNonOrthogonalCorrectors 0;
    pRefCell        0;
    pRefValue       101325;
    residualControl
    {
        p_rgh           1e-5;
        U               1e-5;
        h               1e-5;
    }
}

// Relaxation chosen for CONVERGENCE of the numerics only. It is not a tuning knob
// on any reported quantity: changing it changes how fast the residuals fall, not the
// converged solution, and grid convergence plus the energy-balance closure are what
// acceptance is judged on.
relaxationFactors
{
    fields { rho 1.0; p_rgh 0.7; }
    equations { U 0.7; h 0.7; "(k|epsilon|omega)" 0.7; }
}""")

    gz = "(0 -9.81 0)" if gravity else "(0 0 0)"
    w(out / "constant/g", "uniformDimensionedVectorField", "g",
      f"dimensions      [0 1 -2 0 0 0 0];\nvalue           {gz};", "constant")

    w(out / "constant/thermophysicalProperties", "dictionary", "thermophysicalProperties", f"""thermoType
{{
    type            heRhoThermo;
    mixture         pureMixture;
    transport       const;
    thermo          hConst;
    equationOfState perfectGas;
    specie          specie;
    energy          sensibleEnthalpy;
}}

mixture
{{
    specie          {{ molWeight {MW}; }}
    thermodynamics  {{ Cp {CP}; Hf 0; }}
    transport       {{ mu {MU}; Pr {PR}; }}
}}""", "constant")

    w(out / "constant/momentumTransport", "dictionary", "momentumTransport",
      "simulationType laminar;", "constant")
    w(out / "constant/turbulenceProperties", "dictionary", "turbulenceProperties",
      "simulationType laminar;", "constant")

    wedge = "    front  { type wedge; }\n    back   { type wedge; }\n    axis   { type empty; }"

    w(out / "0/U", "volVectorField", "U", f"""dimensions      [0 1 -1 0 0 0 0];
internalField   uniform (0 {U:.8f} 0);

boundaryField
{{
    inlet  {{ type fixedValue; value uniform (0 {U:.8f} 0); }}
    outlet {{ type zeroGradient; }}
    wall   {{ type noSlip; }}
{wedge}
}}""", "0")

    w(out / "0/T", "volScalarField", "T", f"""dimensions      [0 0 0 1 0 0 0];
internalField   uniform {T0};

boundaryField
{{
    inlet  {{ type fixedValue; value uniform {T0}; }}
    outlet {{ type zeroGradient; }}
    wall
    {{
        type            externalWallHeatFluxTemperature;
        mode            flux;
        q               uniform {q_w};
        kappaMethod     fluidThermo;
        value           uniform {T0};
    }}
{wedge}
}}""", "0")

    w(out / "0/p_rgh", "volScalarField", "p_rgh", f"""dimensions      [1 -1 -2 0 0 0 0];
internalField   uniform {P0};

boundaryField
{{
    inlet  {{ type fixedFluxPressure; value uniform {P0}; }}
    outlet {{ type fixedValue; value uniform {P0}; }}
    wall   {{ type fixedFluxPressure; value uniform {P0}; }}
{wedge}
}}""", "0")

    w(out / "0/p", "volScalarField", "p", f"""dimensions      [1 -1 -2 0 0 0 0];
internalField   uniform {P0};

boundaryField
{{
    inlet  {{ type calculated; value uniform {P0}; }}
    outlet {{ type calculated; value uniform {P0}; }}
    wall   {{ type calculated; value uniform {P0}; }}
{wedge}
}}""", "0")

    meta = {
        "case": out.name, "Re": Re, "q_w_W_m2": q_w, "gravity_on": gravity,
        "mesh": {"nr": nr, "ny": ny, "cells": nr * ny},
        "geometry": {"D_m": D, "L_m": L, "L_over_D": L / D,
                     "wedge_half_angle_deg": HALF_ANGLE_DEG},
        "fluid": {"mu": MU, "Pr": PR, "Cp": CP, "molWeight": MW,
                  "T_inlet_K": T0, "p_K": P0},
        "derived": d, "iterations": n_iter,
        "solver": "buoyantSimpleFoam", "turbulence": "laminar",
    }
    (out / "case.json").write_text(json.dumps(meta, indent=2) + "\n")
    return meta


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=pathlib.Path, required=True)
    ap.add_argument("--Re", type=float, required=True)
    ap.add_argument("--qw", type=float, default=200.0)
    ap.add_argument("--gravity", choices=("on", "off"), required=True)
    ap.add_argument("--nr", type=int, default=30)
    ap.add_argument("--ny", type=int, default=300)
    ap.add_argument("--iters", type=int, default=3000)
    ap.add_argument("--write-interval", type=int, default=500)
    a = ap.parse_args()
    m = build(a.out, a.Re, a.qw, a.gravity == "on", a.nr, a.ny, a.iters, a.write_interval)
    print(json.dumps(m, indent=2))
